# Generated by Django 5.1.4 on 2024-12-22 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteroupas_app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='MarcaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteroupas_app.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=20)),
                ('preco', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=5, null=True)),
                ('categorias', models.ManyToManyField(related_name='produtos', through='siteroupas_app.CategoriaProduto', to='siteroupas_app.categoria')),
                ('marcas', models.ManyToManyField(related_name='produtos', through='siteroupas_app.MarcaProduto', to='siteroupas_app.marca')),
            ],
        ),
        migrations.AddField(
            model_name='marcaproduto',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteroupas_app.produto'),
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteroupas_app.produto'),
        ),
    ]
