# Generated by Django 5.1.4 on 2024-12-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteroupas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='marcas_logos/'),
        ),
    ]
