# Generated by Django 5.1.4 on 2025-01-08 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteroupas_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='color',
        ),
        migrations.CreateModel(
            name='BrandColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteroupas_app.brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteroupas_app.color')),
            ],
        ),
    ]
