# Generated by Django 5.1.4 on 2025-01-06 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteroupas_app', '0003_alter_produto_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='banners/')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='siteroupas_app.marca')),
            ],
        ),
    ]
