# Generated by Django 5.1.4 on 2025-01-06 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteroupas_app', '0005_produto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteroupas_app.categoria'),
        ),
    ]
