# Generated by Django 5.1.4 on 2025-01-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteroupas_app', '0006_alter_produto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='marcas',
        ),
        migrations.AlterField(
            model_name='produto',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
